### ISSUE TITLE
Failed to compile upon adding on react native 0.60

### ISSUE THREAD

**Issue by hansyulian** [tradle/react-native-crypto#37] opened 2019-09-17 04:11 UTC
I got the following error: 

```
error: method does not override or implement a method from a supertype
    @Override
    ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-os:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (D:\_crypto-defense-source-codes\Zynesis\nzia-wallet\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (D:\_crypto-defense-source-codes\Zynesis\nzia-wallet\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at then.result (D:\_crypto-defense-source-codes\Zynesis\nzia-wallet\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NZIAWallet@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the NZIAWallet@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hansy\AppData\Roaming\npm-cache\_logs\2019-09-17T04_03_57_096Z-debug.log
```

**Comment by mvayngrib** [comment] 2019-09-17 14:16
closing as duplicate of https://github.com/tradle/react-native-crypto/issues/34

**Closed as completed by mvayngrib** 2019-09-17 14:16 UTC
