### ISSUE TITLE
Unable to install rn-nodify

### ISSUE THREAD

**Issue by irfman12** [tradle/react-native-crypto#24] opened 2018-01-08 13:24 UTC
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/tradle/rn-nodify.git

I'm getting a timeout, is anonymous access allowed.

**Comment by mvayngrib** [comment] 2018-01-09 22:17
@irfman12 yea, it's a public repository, so not sure what the issue is

**Comment by digitaldavenyc** [comment] 2018-03-02 02:40
+1 for this, got the timeout as well... very strange on a public repo

**Comment by mvayngrib** [comment] 2018-03-02 02:45
@irfman12  just noticed you spelled the package name wrong, it should be rn-nodeify

**Comment by digitaldavenyc** [comment] 2018-03-02 02:48
@mvayngrib I tried that and it still timed out on running `./node_modules/.bin/rn-nodeify --hack --install`

**Comment by digitaldavenyc** [comment] 2018-03-02 02:57
```
not overwriting "buffer"
not overwriting "react-native-crypto"
not overwriting "events"
not overwriting "process"
not overwriting "util"
not overwriting "react-native-randombytes"
not reinstalling assert
not reinstalling inherits
not reinstalling console-browserify
not reinstalling constants-browserify
not reinstalling domain-browser
not reinstalling path-browserify
not reinstalling punycode
not reinstalling querystring-es3
not reinstalling string_decoder
not reinstalling tty-browserify
not reinstalling vm-browserify
installing from npm browserify-zlib
installing from npm dns.js
installing from github react-native-http
installing from npm https-browserify
installing from npm react-native-os
installing from npm react-native-level-fs
installing from npm react-native-udp
installing from npm stream-browserify
installing from npm timers-browserify
installing from npm url
installing from npm react-native-tcp
installing from npm readable-stream
installing: npm install --save browserify-zlib@~0.1.4 dns.js@^1.0.1 tradle/react-native-http#834492d https-browserify@~0.0.0 react-native-os@^1.0.1 react-native-level-fs@^3.0.0 react-native-udp@^2.1.0 stream-browserify@^1.0.0 timers-browserify@^1.0.1 url@~0.10.1 react-native-tcp@^3.2.1 readable-stream@1.0.33

```

Hangs here and doesn't finish `npm install`

**Comment by digitaldavenyc** [comment] 2018-03-02 03:00
Ok really weird, I just ran it for a third time and it worked. I didn't change anything, not sure why but I can compile

**Comment by mvayngrib** [comment] 2018-03-02 03:01
@digitaldavenyc great to hear! No idea what the issue is, maybe something with npm

**Comment by digitaldavenyc** [comment] 2018-03-02 03:01
That was my guess, it does happen sometimes...

**Comment by tofoli** [comment] 2018-03-07 18:52
For me it hangs in the dependency installation 'github react-native-http'

If I run npm only with react-native-http it also hangs
```npm install --save tradle/react-native-http#834492d```

**Comment by mvayngrib** [comment] 2018-03-07 19:11
@tofoli strange, i just tried `npm install --save tradle/react-native-http#834492d` in a fresh folder and had no issues

**Comment by tofoli** [comment] 2018-03-07 19:18
Very strange, as other github repositories I can install normally

**Comment by tofoli** [comment] 2018-03-07 19:20
One more thing, the use of a core of my CPU sits at 100%

**Comment by mvayngrib** [comment] 2018-03-07 19:54
@tofoli published rn-nodeify@10 which uses http published to @tradle/react-native-http

**Comment by mvayngrib** [comment] 2018-04-20 16:08
closing this for now, reopen if the issue recurs

**Closed as completed by mvayngrib** 2018-04-20 16:08 UTC
